services:
  app:
    image: ghcr.io/isnubi/ovh-ks-availability-alerter:latest
    volumes:
      - ./servers.json:/app/servers.json
    environment:
      - NTFY_URL=https://ntfy.example.com/alerting
      - POLL_INTERVAL=60
    restart: unless-stopped
